<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All dumps successfully removed.' => 'Все дампы успешно удалены.',
    'Create dump' => 'Сделать дамп',
    'Create time' => 'Время создания',
    'DB manager' => 'БД менеджер',
    'Delete' => 'Удалить',
    'Delete all' => 'Удалить всё',
    'Download' => 'Скачать',
    'Dump deleted successfully.' => 'Дамп успешно удален.',
    'Dump successfully created.' => 'Дамп успешно создан.',
    'Dump successfully restored.' => 'Дамп успешно восстановлен.',
    'Error deleting dump.' => 'Ошибка удаления дампа.',
    'Error deleting dumps.' => 'Ошибка удаления дампов.',
    'Name' => 'Имя',
    'Restore' => 'Восстановить',
    'Size' => 'Размер',
	'Type'=>'Тип',
	'Are you sure?'=>'Вы уверены?',
	'As archive'=>'Архивировать?',
	'Database'=>'Соединение с базой',
	'Dump only schema'=>'Дамп структуры, без данных',
	'Custom dump preset' => 'Свой шаблон опций для дампа',
	'run in background' =>'Запустить в фоне',
	'Dump process running with pid={pid}'=>'Процесс запущен с pid={pid}',
	'Dump request invalid'=>'Ошибка запроса дампа'
];
