<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active processes:' => 'Активные процессы:',
    'All dumps successfully removed.' => 'Все дампы успешно удалены.',
    'Are you sure?' => 'Вы уверены?',
    'Create dump' => 'Сделать дамп',
    'Create time' => 'Время создания',
    'Custom dump preset' => 'Свой шаблон опций для дампа',
    'Custom restore preset' => 'Свой шаблон опций для восстановлений',
    'DB manager' => 'БД менеджер',
    'Database' => 'База данных',
    'Delete' => 'Удалить',
    'Delete all' => 'Удалить всё',
    'Delete from storage' => 'Удалить из хранилища',
    'Download' => 'Скачать',
    'Dump deleted from storage.' => 'Дамп удалён из хранилища.',
    'Dump deleted successfully.' => 'Дамп успешно удален.',
    'Dump failed.' => 'Ошибка создания дампа.',
    'Dump only schema' => 'Дамп структуры без данных',
    'Dump request invalid.' => 'Ошибка запроса дампа.',
    'Dump successfully created.' => 'Дамп успешно создан.',
    'Dump successfully restored.' => 'Дамп успешно восстановлен.',
    'Dump uploaded to storage.' => 'Дамп загружен в хранилище.',
    'Error deleting dump.' => 'Ошибка удаления дампа.',
    'Error deleting dumps.' => 'Ошибка удаления дампов.',
    'Name' => 'Имя',
    'Process complete!' => 'Задача выполнена!',
    'Process running with pid={pid}' => 'Процесс запущен с pid={pid}',
    'Restore' => 'Восстановить',
    'Restore failed.' => 'Ошибка восстановления.',
    'Run in background' => 'Запустить в фоне',
    'Size' => 'Размер',
    'Type' => 'Тип',
    'Upload from storage' => 'Загрузить в хранилище',
    'gzip' => '',
];
