<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DB manager' => 'БД менеджер',
    'Database' => 'База даних',
    'gzip' => 'gzip',
    'Dump only schema' => 'Дамп структури без даних',
    'Custom dump preset' => 'Свій шаблон опцій для дампу',
    'Run in background' => 'Запустити у фоні',
    'Create dump' => 'Створити дамп',
    'Delete all' => 'Видалити все',
    'Are you sure?' => 'Ви впевнені?',
    'Type' => 'Тип',
    'Name' => 'Ім\'я',
    'Size' => 'Розмір',
    'Create time' => 'Час створення',
    'Active processes:' => 'Активні процеси:',
    'All dumps successfully removed.' => 'Усі дампи успішно видалено.',
    'Custom restore preset' => 'Свій шаблон опцій для відновлень',
    'Delete' => 'Видалити',
    'Delete from storage' => 'Видалити зі сховища',
    'Download' => 'Завантажити',
    'Dump deleted from storage.' => 'Дамп видалено зі сховища.',
    'Dump deleted successfully.' => 'Дамп успішно видалено.',
    'Dump failed.' => 'Помилка при створенні дампу.',
    'Dump request invalid.' => 'Помилка запиту дампу.',
    'Dump successfully created.' => 'Дамп успішно створено.',
    'Dump successfully restored.' => 'Дамп успішно відновлено.',
    'Dump uploaded to storage.' => 'Дамп завантажено у сховище.',
    'Error deleting dump.' => 'Помилка видалення дампу.',
    'Error deleting dumps.' => 'Помилка видалення дампів.',
    'Process complete!' => 'Завдання виконано!',
    'Process running with pid={pid}' => 'Процесс запущено з pid={pid}',
    'Restore' => 'Відновити',
    'Restore failed.' => 'Помилка відновлення.',
    'Upload to storage' => 'Завантажити до сховища',
    'gzip' => '',
];
